"""empty message

Revision ID: 290f2001232d
Revises: 09be4e11ea47
Create Date: 2023-02-11 17:15:12.703827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290f2001232d'
down_revision = '09be4e11ea47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('button_uz', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('button_ru', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('button_en', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'button_en')
    op.drop_column('courses', 'button_ru')
    op.drop_column('courses', 'button_uz')
    # ### end Alembic commands ###
