"""empty message

Revision ID: 486289cfb047
Revises: 1c2737d02208
Create Date: 2023-01-04 10:44:41.196225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486289cfb047'
down_revision = '1c2737d02208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('info_ru', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'info_ru')
    # ### end Alembic commands ###
