"""empty message

Revision ID: 4942d1c2a9c3
Revises: 22d8b1add752
Create Date: 2023-01-04 13:25:51.061449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4942d1c2a9c3'
down_revision = '22d8b1add752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_uz', sa.String(), nullable=True),
    sa.Column('image_en', sa.String(), nullable=True),
    sa.Column('image_ru', sa.String(), nullable=True),
    sa.Column('info_uz', sa.Text(), nullable=True),
    sa.Column('info_ru', sa.Text(), nullable=True),
    sa.Column('info_en', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='teacherstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers')
    # ### end Alembic commands ###
