"""empty message

Revision ID: 651ce36060dd
Revises: 3387e7e4cea9
Create Date: 2023-01-04 11:47:56.453526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651ce36060dd'
down_revision = '3387e7e4cea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
