"""empty message

Revision ID: aafffb81fd2c
Revises: 290f2001232d
Create Date: 2023-02-12 10:57:03.486363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aafffb81fd2c'
down_revision = '290f2001232d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advantage', sa.Column('button_uz', sa.String(), nullable=True))
    op.add_column('advantage', sa.Column('button_ru', sa.String(), nullable=True))
    op.add_column('advantage', sa.Column('button_en', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advantage', 'button_en')
    op.drop_column('advantage', 'button_ru')
    op.drop_column('advantage', 'button_uz')
    # ### end Alembic commands ###
