"""empty message

Revision ID: bc2d05717eb3
Revises: 651ce36060dd
Create Date: 2023-01-04 11:49:24.758626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc2d05717eb3'
down_revision = '651ce36060dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
