from . import bot_settings
from . import advantage
from . import about
from . import contact
from . import results
from . import teachers
from . import admin_courses
from . import admin_statistics
from . import select_language
from . import admin_backs
from . import send_post
from . import start
